#!/usr/bin/env bash
# tgrep installer — installs tgrep and creates an rg wrapper.
#
# Usage:
#   ./install.sh [--prefix DIR] [--uninstall]
#
# Default prefix: ~/.local
#
# What it does:
#   1. Builds tgrep in release mode (cargo build --release)
#   2. Finds the real ripgrep (rg) binary
#   3. Installs tgrep to $PREFIX/bin/tgrep
#   4. Creates an rg wrapper at $PREFIX/bin/rg that routes to tgrep
#   5. Stores the real rg path for delegation
#
# After installation, `rg` commands are transparently routed:
#   - Indexed searches → tgrep (faster)
#   - Unsupported flags / no index → real ripgrep (identical behavior)
#
# Uninstall:
#   ./install.sh --uninstall
#   This removes the wrapper and restores direct rg access.

set -euo pipefail

PREFIX="$HOME/.local"
UNINSTALL=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix)
            PREFIX="$2"
            shift 2
            ;;
        --uninstall)
            UNINSTALL=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [--prefix DIR] [--uninstall]"
            echo ""
            echo "  --prefix DIR   Install prefix (default: ~/.local)"
            echo "  --uninstall    Remove tgrep and restore direct rg access"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

BIN_DIR="$PREFIX/bin"
CONFIG_DIR="$HOME/.config/tgrep"

# ── Uninstall ────────────────────────────────────────────────────────

if $UNINSTALL; then
    echo "Uninstalling tgrep..."
    rm -f "$BIN_DIR/tgrep" 2>/dev/null || true
    rm -f "$BIN_DIR/rg" 2>/dev/null || true
    rm -rf "$CONFIG_DIR" 2>/dev/null || true
    echo "Done. rg now uses the system ripgrep directly."
    echo "Note: tgrep state directory (~/.local/state/tgrep) is preserved."
    echo "      Remove it manually if you want to clear all index data:"
    echo "      rm -rf ~/.local/state/tgrep"
    exit 0
fi

# ── Install ──────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== tgrep installer ==="
echo ""

# 1. Build tgrep (using compile.sh for CPU auto-detection)
echo "[1/5] Building tgrep (release mode, auto-detecting CPU features)..."
cd "$SCRIPT_DIR"
./compile.sh --release
if [ ! -f "target/release/tgrep" ]; then
    echo "Error: tgrep binary not found after build" >&2
    exit 1
fi
echo "      Build complete."
echo ""

# 2. Find real rg
echo "[2/5] Locating real ripgrep..."
REAL_RG=""

# Try `which rg` but skip our own wrapper
for candidate in $(which -a rg 2>/dev/null || true); do
    # Skip if this is our own wrapper (contains TGREP_REAL_RG anywhere)
    if grep -q "TGREP_REAL_RG" "$candidate" 2>/dev/null; then
        continue
    fi
    # Skip if this is the tgrep binary
    if [ "$(readlink -f "$candidate" 2>/dev/null)" = "$(readlink -f "$SCRIPT_DIR/target/release/tgrep" 2>/dev/null)" ]; then
        continue
    fi
    REAL_RG="$candidate"
    break
done

# Fallback: check common locations
if [ -z "$REAL_RG" ]; then
    for path in /usr/bin/rg /usr/local/bin/rg /opt/homebrew/bin/rg /snap/bin/rg; do
        if [ -x "$path" ]; then
            REAL_RG="$path"
            break
        fi
    done
fi

if [ -z "$REAL_RG" ]; then
    echo "Error: Could not find ripgrep (rg) binary." >&2
    echo "       Install ripgrep first, then re-run this installer." >&2
    exit 1
fi

# Verify it's actually ripgrep
if ! "$REAL_RG" --version 2>/dev/null | head -1 | grep -q "ripgrep"; then
    echo "Warning: $REAL_RG doesn't appear to be ripgrep." >&2
    echo "         Proceeding anyway..." >&2
fi

echo "      Found: $REAL_RG ($("$REAL_RG" --version 2>/dev/null | head -1))"
echo ""

# 3. Install tgrep binary
echo "[3/5] Installing tgrep to $BIN_DIR/..."
mkdir -p "$BIN_DIR"
cp "target/release/tgrep" "$BIN_DIR/tgrep"
chmod +x "$BIN_DIR/tgrep"
echo "      Installed: $BIN_DIR/tgrep"
echo ""

# 4. Create rg wrapper
echo "[4/5] Creating rg wrapper at $BIN_DIR/rg..."
cat > "$BIN_DIR/rg" << WRAPPER
#!/bin/sh
# tgrep rg wrapper — auto-generated by tgrep install.sh
# Routes rg commands to tgrep (indexed) or real ripgrep (fallback).
# To uninstall: run install.sh --uninstall
export TGREP_REAL_RG="$REAL_RG"
exec "$BIN_DIR/tgrep" "\$@"
WRAPPER
chmod +x "$BIN_DIR/rg"
echo "      Created: $BIN_DIR/rg"
echo ""

# 5. Store config
echo "[5/5] Storing configuration..."
mkdir -p "$CONFIG_DIR"
echo "$REAL_RG" > "$CONFIG_DIR/rg_path"
echo "      Config: $CONFIG_DIR/rg_path"
echo ""

# Verify PATH
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    echo "Warning: $BIN_DIR is not in your PATH." >&2
    echo "         Add this line to your shell config (~/.bashrc or ~/.zshrc):" >&2
    echo "         export PATH=\"$BIN_DIR:\$PATH\"" >&2
    echo ""
fi

echo "=== Installation complete ==="
echo ""
echo "tgrep is now installed. The 'rg' command will use tgrep's index"
echo "when available, and fall back to real ripgrep for everything else."
echo ""
echo "To build an index for your codebase:"
echo "  tgrep index build /path/to/code"
echo ""
echo "To check index status:"
echo "  tgrep index status"
echo ""
echo "To uninstall:"
echo "  $0 --uninstall"
