#!/usr/bin/env bash
# tgrep installer — installs tgrep and creates an rg wrapper.
#
# Usage:
#   ./install.sh [--prefix DIR] [--uninstall] [--index] [--no-index]
#                [--zfs] [--no-zfs]
#
# Default prefix: ~/.local
#
# What it does:
#   1. Builds tgrep in release mode (cargo build --release)
#   2. Finds the real ripgrep (rg) binary
#   3. Installs tgrep to $PREFIX/bin/tgrep
#   4. Creates an rg wrapper at $PREFIX/bin/rg that routes to tgrep
#   5. Stores the real rg path for delegation
#   6. Offers a compressed ZFS dataset for the index (when ZFS is present)
#   7. Offers to build a systemwide index
#
# After installation, `rg` commands are transparently routed:
#   - Indexed searches → tgrep (faster)
#   - Unsupported flags / no index → real ripgrep (identical behavior)
#
# Uninstall:
#   ./install.sh --uninstall
#   This removes the wrapper and restores direct rg access.

set -euo pipefail

PREFIX="$HOME/.local"
UNINSTALL=false
WANT_INDEX=""    # "" = ask (TTY only), "yes", "no"
WANT_ZFS=""      # "" = ask (TTY only), "yes", "no"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix)
            PREFIX="$2"
            shift 2
            ;;
        --uninstall)
            UNINSTALL=true
            shift
            ;;
        --index)
            WANT_INDEX="yes"
            shift
            ;;
        --no-index)
            WANT_INDEX="no"
            shift
            ;;
        --zfs)
            WANT_ZFS="yes"
            shift
            ;;
        --no-zfs)
            WANT_ZFS="no"
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [--prefix DIR] [--uninstall] [--index|--no-index] [--zfs|--no-zfs]"
            echo ""
            echo "  --prefix DIR    Install prefix (default: ~/.local)"
            echo "  --index         Build a systemwide index without asking"
            echo "  --no-index      Skip the index-build offer"
            echo "  --zfs           Place the index on a ZFS dataset without asking"
            echo "  --no-zfs        Skip the ZFS offer"
            echo "  --uninstall     Remove tgrep and restore direct rg access"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

BIN_DIR="$PREFIX/bin"
CONFIG_DIR="$HOME/.config/tgrep"

# ── Uninstall ────────────────────────────────────────────────────────

if $UNINSTALL; then
    echo "Uninstalling tgrep..."
    rm -f "$BIN_DIR/tgrep" 2>/dev/null || true
    rm -f "$BIN_DIR/rg" 2>/dev/null || true
    rm -rf "$CONFIG_DIR" 2>/dev/null || true
    echo "Done. rg now uses the system ripgrep directly."
    echo "Note: tgrep state directory (~/.local/state/tgrep) is preserved."
    echo "      Remove it manually if you want to clear all index data:"
    echo "      rm -rf ~/.local/state/tgrep"
    exit 0
fi

# ── Install ──────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== tgrep installer ==="
echo ""

# 1. Build tgrep (using compile.sh for CPU auto-detection)
echo "[1/5] Building tgrep (release mode, auto-detecting CPU features)..."
cd "$SCRIPT_DIR"
./compile.sh --release
if [ ! -f "target/release/tgrep" ]; then
    echo "Error: tgrep binary not found after build" >&2
    exit 1
fi
echo "      Build complete."
echo ""

# 2. Find real rg
echo "[2/5] Locating real ripgrep..."
REAL_RG=""

# Try `which rg` but skip our own wrapper
for candidate in $(which -a rg 2>/dev/null || true); do
    # Skip if this is our own wrapper (contains TGREP_REAL_RG anywhere)
    if grep -q "TGREP_REAL_RG" "$candidate" 2>/dev/null; then
        continue
    fi
    # Skip if this is the tgrep binary
    if [ "$(readlink -f "$candidate" 2>/dev/null)" = "$(readlink -f "$SCRIPT_DIR/target/release/tgrep" 2>/dev/null)" ]; then
        continue
    fi
    REAL_RG="$candidate"
    break
done

# Fallback: check common locations
if [ -z "$REAL_RG" ]; then
    for path in /usr/bin/rg /usr/local/bin/rg /opt/homebrew/bin/rg /snap/bin/rg; do
        if [ -x "$path" ]; then
            REAL_RG="$path"
            break
        fi
    done
fi

if [ -z "$REAL_RG" ]; then
    echo "Error: Could not find ripgrep (rg) binary." >&2
    echo "       Install ripgrep first, then re-run this installer." >&2
    exit 1
fi

# Verify it's actually ripgrep
if ! "$REAL_RG" --version 2>/dev/null | head -1 | grep -q "ripgrep"; then
    echo "Warning: $REAL_RG doesn't appear to be ripgrep." >&2
    echo "         Proceeding anyway..." >&2
fi

echo "      Found: $REAL_RG ($("$REAL_RG" --version 2>/dev/null | head -1))"
echo ""

# 3. Install tgrep binary
echo "[3/5] Installing tgrep to $BIN_DIR/..."
mkdir -p "$BIN_DIR"
cp "target/release/tgrep" "$BIN_DIR/tgrep"
chmod +x "$BIN_DIR/tgrep"
echo "      Installed: $BIN_DIR/tgrep"
echo ""

# 4. Create rg wrapper
echo "[4/5] Creating rg wrapper at $BIN_DIR/rg..."
cat > "$BIN_DIR/rg" << WRAPPER
#!/bin/sh
# tgrep rg wrapper — auto-generated by tgrep install.sh
# Routes rg commands to tgrep (indexed) or real ripgrep (fallback).
# To uninstall: run install.sh --uninstall
export TGREP_REAL_RG="$REAL_RG"
exec "$BIN_DIR/tgrep" "\$@"
WRAPPER
chmod +x "$BIN_DIR/rg"
echo "      Created: $BIN_DIR/rg"
echo ""

# 5. Store config
echo "[5/5] Storing configuration..."
mkdir -p "$CONFIG_DIR"
echo "$REAL_RG" > "$CONFIG_DIR/rg_path"
echo "      Config: $CONFIG_DIR/rg_path"
echo ""

# Verify PATH
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    echo "Warning: $BIN_DIR is not in your PATH." >&2
    echo "         Add this line to your shell config (~/.bashrc or ~/.zshrc):" >&2
    echo "         export PATH=\"$BIN_DIR:\$PATH\"" >&2
    echo ""
fi

echo "=== Installation complete ==="
echo ""
echo "tgrep is now installed. The 'rg' command will use tgrep's index"
echo "when available, and fall back to real ripgrep for everything else."
echo ""

# ── 6. Optional: ZFS-backed index dataset ────────────────────────────

STATE_DIR="$HOME/.local/state/tgrep"

ask() {  # ask "question" -> 0 if yes; only prompts when stdin is a TTY
    local q="$1"
    if [[ -n "$WANT_ZFS" && "$q" == *ZFS* ]]; then
        [[ "$WANT_ZFS" == "yes" ]]
        return
    fi
    if [[ -n "$WANT_INDEX" && "$q" == *index* ]]; then
        [[ "$WANT_INDEX" == "yes" ]]
        return
    fi
    [[ -t 0 ]] || return 1
    local a
    read -r -p "$q [y/N] " a
    [[ "$a" =~ ^[Yy] ]]
}

if command -v zfs >/dev/null 2>&1 && command -v zpool >/dev/null 2>&1; then
    POOL="$(zpool list -H -o name 2>/dev/null | head -1 || true)"
    if [[ -n "$POOL" ]]; then
        echo "ZFS detected (pool: $POOL)."
        echo "  A native ZFS dataset is the best home for the tgrep index:"
        echo "  transparent zstd compression shrinks it ~2-3x, the ARC keeps"
        echo "  hot trigram blocks in RAM, and snapshots give you free rollback."
        if ask "Create ZFS dataset $POOL/tgrep for the index (uses sudo)?"; then
            if ! zfs list "$POOL/tgrep" >/dev/null 2>&1; then
                if sudo zfs create -o compression=zstd -o atime=off \
                    -o mountpoint="$STATE_DIR" "$POOL/tgrep"; then
                    sudo chown "$(id -u):$(id -g)" "$STATE_DIR"
                    echo "      Created: $POOL/tgrep mounted at $STATE_DIR"
                else
                    echo "      zfs create failed — keeping the plain directory." >&2
                fi
            else
                echo "      Dataset $POOL/tgrep already exists — leaving it alone."
                echo "      To use it here: sudo zfs set mountpoint=$STATE_DIR $POOL/tgrep"
            fi
        else
            echo "      Skipping ZFS setup (index will live in a plain directory)."
        fi
        echo ""
    fi
fi

# ── 7. Optional: build a systemwide index ────────────────────────────

echo "The rg wrapper only accelerates searches over indexed paths."
if ask "Build a systemwide index now?"; then
    echo ""
    echo "  What should tgrep index?"
    echo "    [1] Your home directory ($HOME)  — recommended"
    echo "    [2] The entire system (/)        — large; needs sudo for some paths"
    echo "    [3] Custom paths"
    CHOICE=""
    if [[ -n "$WANT_INDEX" && "$WANT_INDEX" == "yes" && ! -t 0 ]]; then
        CHOICE="1"
    else
        read -r -p "  Choice [1]: " CHOICE
    fi
    CHOICE="${CHOICE:-1}"
    case "$CHOICE" in
        1)
            echo "      Indexing $HOME (this can take a few minutes)..."
            "$BIN_DIR/tgrep" index build "$HOME" || true
            ;;
        2)
            echo "      WARNING: indexing / reads every readable file and can"
            echo "      produce a multi-GB index. Ctrl-C to abort."
            sleep 3
            sudo "$BIN_DIR/tgrep" index build / || true
            ;;
        3)
            read -r -p "  Paths to index (space-separated): " INDEX_PATHS
            if [[ -n "${INDEX_PATHS:-}" ]]; then
                # shellcheck disable=SC2086
                "$BIN_DIR/tgrep" index build $INDEX_PATHS || true
            fi
            ;;
        *)
            echo "      Unknown choice — skipping."
            ;;
    esac
else
    echo ""
    echo "Skipped. Build one any time:"
    echo "  tgrep index build /path/to/code"
fi
echo ""

echo "Useful commands:"
echo "  tgrep index status     — indexed paths, segments, cache stats"
echo "  tgrep index build DIR  — (re)index a path"
echo "  tgrep cache clear      — drop cached search results"
echo ""
echo "To uninstall:"
echo "  $0 --uninstall"
